<?php

/**
 * @file
 * Hook implementations for the vsite module.
 */

use Drupal\bibcite_entity\Entity\ReferenceInterface;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node\NodeInterface;
use Drupal\views\Plugin\views\cache\CachePluginBase;
use Drupal\vsite_preset\Entity\GroupPreset;
use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Url;
use Drupal\group\Entity\GroupInterface;
use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;
use Drupal\vsite\Cache\VsiteCacheContext;

/**
 * Implements hook_modules_installed().
 */
function vsite_modules_installed(array $modules) {
  vsite_setup_new_apps();
}

/**
 * Sets up associations between app content and group types.
 *
 * @todo this needs work
 */
function vsite_setup_new_apps() {
  // TODO: Fix this so it doesn't block installs.
}

/**
 * Implements hook_views_data_alter().
 */
function vsite_views_data_alter(&$data) {
  $data['group_content']['current_vsite_filter'] = [
    'title' => t('Current Vsite Filter'),
    'filter' => [
      'title' => t('Current Vsite Filter'),
      'help' => 'Filters content on the current vsite',
      'field' => 'gid',
      'id' => 'vsite_current_filter',
    ],
  ];
  $data['groups']['subsite_vsite_filter'] = [
    'title' => t('Subsite Filter'),
    'filter' => [
      'title' => t('Subsite Filter'),
      'help' => 'Filters child sites on the current vsite',
      'field' => 'field_parent_site',
      'id' => 'vsite_subsite_filter',
    ],
  ];
}

/**
 * Implements hook_form_node_form_alter().
 */
function vsite_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\vsite\Plugin\VsiteContextManagerInterface $vsiteContext */
  $vsiteContext = \Drupal::service('vsite.context_manager');

  if ($group = $vsiteContext->getActiveVsite()) {
    /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
    $entity = $form_state->getFormObject()->getEntity();
    $plugin_id = 'group_node:' . $entity->bundle();
    if ($entity->isNew() || !$group->getContentByEntityId($plugin_id, $entity->id())) {
      $form_state->set('group', $group);
      $form_state->set('group_content_enabler', 'group_node:' . $entity->bundle());
      foreach (Element::children($form['actions']) as $name) {

        // Skip buttons without submit handlers.
        if (empty($form['actions'][$name]['#submit'])) {
          continue;
        }

        // Skip buttons that do not properly build and save an entity.
        $submit = $form['actions'][$name]['#submit'];
        if (!in_array('::submitForm', $submit) || !in_array('::save', $submit)) {
          continue;
        }

        // If we are using the wizard, we need to substitute the entity save
        // handler in order to add the entity to the private temp store.
        $form['actions'][$name]['#submit'][] = 'group_content_entity_submit';
      }
    }
    $form['actions']['preview']['#submit'][] = 'vsite_node_preview_submit';
  }
  Drupal::service('vsite.form_delete_destination')->setDeleteButtonDestination($form, $form_state);
}

/**
 * Implements hook_form_bibcite_reference_form_alter().
 */
function vsite_form_bibcite_reference_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  Drupal::service('vsite.form_delete_destination')->setDeleteButtonDestination($form, $form_state);
}

/**
 * Implements hook_form_views_ui_config_item_form_alter().
 */
function vsite_form_views_ui_config_item_form_alter(&$form, FormStateInterface $form_state) {
  $token_items = [];
  $token_helper = \Drupal::service('vsite.token_helper');
  $available_tokens = $token_helper->getAvailableGlobalTokens(
    FALSE,
    [
      'vsite',
      'site',
      'view',
    ]
  );
  foreach ($available_tokens as $type => $tokens) {
    $item = [
      '#markup' => $type,
      'children' => [],
    ];
    foreach ($tokens as $name => $info) {
      $item['children'][$name] = "[$type:$name]" . ' - ' . $info['name'] . ': ' . $info['description'];
    }

    $token_items[$type] = $item;
  }
  $form['options']['global_tokens']['list'] = [
    '#theme' => 'item_list',
    '#items' => $token_items,
    '#attributes' => [
      'class' => ['global-tokens'],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function vsite_form_alter(&$form, FormStateInterface $formState, $form_id) {
  /** @var \Drupal\vsite\Plugin\VsiteContextManagerInterface $vsiteContext */
  $vsiteContext = \Drupal::service('vsite.context_manager');

  if ($formState->getFormObject() instanceof EntityFormInterface) {

    /** @var \Drupal\Core\Entity\EntityInterface $entity */
    $entity = $formState->getFormObject()->getEntity();
    $entityTypeId = $entity->getEntityTypeId();
    /** @var \Drupal\group\Entity\GroupInterface $group */
    if ($group = $vsiteContext->getActiveVsite()) {
      $groupTypeId = $group->bundle();

      /** @var \Drupal\group\Plugin\GroupContentEnablerManagerInterface $groupContentEnabler */
      $groupContentEnabler = \Drupal::service('plugin.manager.group_content_enabler');
      $plugins = $groupContentEnabler->getGroupTypePluginMap();
      $availablePlugins = $plugins[$groupTypeId];

      $plugin_id = 'group_entity:' . $entity->getEntityTypeId();
      if (in_array($plugin_id, $availablePlugins) && ($entity->isNew() || !($group->getContentByEntityId($plugin_id, $entity->id())))) {
        $formState->set('group', $group);
        $formState->set('group_content_enabler', $plugin_id);
        foreach (Element::children($form['actions']) as $name) {

          // Skip buttons without submit handlers.
          if (empty($form['actions'][$name]['#submit'])) {
            continue;
          }

          // Skip buttons that do not properly build and save an entity.
          $submit = $form['actions'][$name]['#submit'];
          if (!in_array('::submitForm', $submit) || !in_array('::save', $submit)) {
            continue;
          }

          // If we are using the wizard, we need to substitute the entity save
          // handler in order to add the entity to the private temp store.
          $form['actions'][$name]['#submit'][] = 'group_content_entity_submit';

          // Set current form as redirect for term creation.
          if ($entityTypeId == 'taxonomy_term' && $entity->isNew()) {
            $form['actions'][$name]['#submit'][] = 'vsite_term_create_redirect_submit';
          }
        }
      }
      if (!empty($form['path']['widget'][0]['alias'])) {
        $purl = $vsiteContext->getActivePurl();
        $current_url = Url::fromRoute('<front>', [], ["absolute" => TRUE])->toString();
        $form['path']['widget'][0]['alias']['#field_prefix'] = $current_url;
        $alias = $form['path']['widget'][0]['alias']['#default_value'];
        $user_input = $formState->getUserInput();
        if (!empty($user_input['path'][0]['alias'])) {
          $alias = $user_input['path'][0]['alias'];
        }
        $alias_without_purl = preg_replace('$^/' . $purl . '$', '', $alias);
        $form['path']['widget'][0]['alias']['#default_value'] = $alias_without_purl;
        $form['#validate'][] = 'vsite_path_widget_check_empty_validate';
        $form['path']['widget'][0]['alias']['#element_validate'][] = 'vsite_path_widget_check_slash_validate';
      }
    }
    $allowedSubSites = \Drupal::config('vsite.settings')->get('allowed_subsite_group_types');
    if (!empty($allowedSubSites) && $entityTypeId == 'group' && !in_array($entity->bundle(), $allowedSubSites)) {
      $form['field_parent_site']['#access'] = FALSE;
    }
  }
  elseif ($formState->getFormObject() instanceof ConfigFormBase && \Drupal::currentUser()->hasPermission('administer presets')) {
    if ($vsite = $vsiteContext->getActiveVsite()) {
      if ($vsite->hasField('field_preset') && !$vsite->get('field_preset')->isEmpty()) {
        $preset_id = $vsite->get('field_preset')->get(0)->getValue()['target_id'];
        $preset = GroupPreset::load($preset_id);
        $form['actions']['submitToPreset'] = [
          '#type' => 'submit',
          '#value' => t('Save To Preset @label', ['@label' => $preset->label()]),
          '#submit' => [
            [$preset, 'saveConfig'],
          ],
        ];
      }
    }
  }
}

/**
 * Set redirect to current page for term creation.
 */
function vsite_term_create_redirect_submit(&$form, FormStateInterface $form_state) {
  $form_state->setRedirect('<current>');
}

/**
 * Validate empty path alias.
 */
function vsite_path_widget_check_empty_validate(&$form, FormStateInterface $form_state) {
  $path_value = $form_state->getValue('path');
  if (isset($path_value[0]['pathauto']) && $path_value[0]['pathauto'] === 0) {
    $alias = trim($path_value[0]['alias'], '/');
    if (empty($alias)) {
      $form_state->setErrorByName('path][0][alias', 'URL alias can not be empty.');
    }
  }
}

/**
 * Validate slash in first char alias.
 */
function vsite_path_widget_check_slash_validate(&$element, FormStateInterface $form_state) {
  $path_value = $form_state->getValue('path');
  if (!empty($path_value[0]['alias'])) {
    if (strpos($path_value[0]['alias'], '/') !== 0) {
      $fixed_alias = '/' . $path_value[0]['alias'];
      $element['#value'] = $fixed_alias;
    }
  }
}

/**
 * Implements hook_views_pre_build().
 */
function vsite_views_pre_build(ViewExecutable $view) {
  if (!empty($view->filter['current_vsite_filter'])) {
    /** @var \Drupal\vsite\Plugin\VsiteContextManagerInterface $vsiteContext */
    $vsiteContext = \Drupal::service('vsite.context_manager');
    if ($vsiteContext->getActiveVsite()) {
      $view->element['#cache']['contexts'][] = 'vsite:' . $vsiteContext->getActiveVsite()->id();
    }
    else {
      $view->element['#cache']['contexts'][] = 'vsite:none';
    }
  }
}

/**
 * Implements hook_toolbar_alter().
 */
function vsite_toolbar_alter(&$toolbar) {
  $toolbar['toolbar_menu_control_panel']['tray']['toolbar_menu_control_panel_links']['#pre_render'][] = '_vsite_prerender_control_panel_links';
}

/**
 * Adds the current vsite to list of this build array's cache contexts.
 *
 * @param array $element
 *   The full toolbar render array.
 *
 * @return array
 *   The modified element
 */
function _vsite_prerender_control_panel_links(array $element) {
  /** @var \Drupal\vsite\Plugin\VsiteContextManagerInterface $vsiteContext */
  $vsiteContext = \Drupal::service('vsite.context_manager');
  $metadata = CacheableMetadata::createFromRenderArray($element['toolbar_menu_control-panel']);
  if ($vsiteContext->getActiveVsite()) {
    $metadata->addCacheContexts(['vsite:' . $vsiteContext->getActiveVsite()->id()]);
  }
  else {
    $metadata->addCacheContexts([VsiteCacheContext::VSITE_CACHE_CONTEXTS_NONE]);
  }

  $metadata->applyTo($element['toolbar_menu_control-panel']);

  return $element;
}

/**
 * Implements hook_library_info_alter().
 */
function vsite_library_info_alter(&$libraries, $extension) {
  if ($extension == 'core' && isset($libraries['drupal.ajax'])) {
    $path = '/' . drupal_get_path('module', 'vsite') . '/js/vsite.ajaxContext.js';
    $libraries['drupal.ajax']['js'][$path] = [
      'weight' => 0,
    ];
  }
}

/**
 * Implements hook_js_alter().
 *
 * Forces the version for this file to be different from core.
 */
function vsite_js_alter(&$js) {
  $path = drupal_get_path('module', 'vsite') . '/js/vsite.ajaxContext.js';
  if (isset($js[$path])) {
    $js[$path]['version'] = '1.0';
  }
}

/**
 * Implements hook_page_attachments().
 */
function vsite_page_attachments(array &$attachments) {
  /** @var \Drupal\vsite\Plugin\VsiteContextManagerInterface $vsiteContext */
  $vsiteContext = \Drupal::service('vsite.context_manager');
  /** @var \Drupal\group\Entity\GroupInterface $vsite */
  if ($vsite = $vsiteContext->getActiveVsite()) {
    $attachments['#attached']['drupalSettings']['spaces'] = [
      'id' => $vsite->id(),
      'label' => $vsite->label(),
      'purl' => $vsiteContext->getActivePurl(),
      'url' => $vsiteContext->getActiveVsiteAbsoluteUrl(),
    ];
  }
}

/**
 * Get all group id that related with field parent site.
 *
 * @param \Drupal\group\Entity\GroupInterface $group
 *   Parent group entity.
 *
 * @return array|int
 *   List of the related and parent gids.
 */
function _vsite_get_group_and_subsite_ids(GroupInterface $group) {
  $query = \Drupal::entityQuery('group')
    ->condition('field_parent_site', $group->id());

  $gids = $query->execute();
  // Add parent group to list.
  $gids[$group->id()] = $group->id();
  return $gids;
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function vsite_node_view_alter(array &$build, NodeInterface $entity, EntityViewDisplayInterface $display) {
  // Makes sure that the destination parameter in contextual links in node
  // full-views are correct.
  // For edit, it should direct to the node page.
  // For delete, it should direct to the node's listing.
  if ($build['#view_mode'] === 'full') {
    $build['#attached']['library'][] = 'vsite/contextualFullView';
    $build['#attached']['drupalSettings']['entitySetting'] = [
      'type' => $entity->getEntityTypeId(),
      'bundle' => $entity->bundle(),
      'mapping' => Drupal::service('vsite.form_delete_destination')::REDIRECT_MAPPING,
    ];
  }
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function vsite_bibcite_reference_view_alter(array &$build, ReferenceInterface $entity, EntityViewDisplayInterface $display) {
  // Makes sure that the destination parameter in contextual links in
  // publication full-view and listing are correct.
  // For edit, it should direct to the publication's full-view.
  // For delete, it should direct to the publications listing.
  if (in_array($build['#view_mode'], ['citation', 'teaser'])) {
    $build['#attached']['library'][] = 'vsite/contextualFullView';
    $build['#attached']['drupalSettings']['entitySetting'] = [
      'type' => $entity->getEntityTypeId(),
      'bundle' => $entity->bundle(),
      'mapping' => Drupal::service('vsite.form_delete_destination')::REDIRECT_MAPPING,
    ];
  }
}

/**
 * Implements hook_views_post_render().
 */
function vsite_views_post_render(ViewExecutable $view, &$output, CachePluginBase $cache) {
  // Makes sure that destination parameter in contextual links in listings are
  // correct. They should be directing to the listing itself.
  $view->element['#attached']['library'][] = 'vsite/contextualList';
}

/**
 * Fixes breaking preview for all nodes/content types.
 *
 * @param array $form
 *   Form itself.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function vsite_node_preview_submit(array $form, FormStateInterface $form_state) {
  // New method introduced in the patch.
  // See https://www.drupal.org/project/drupal/issues/2950883
  $form_state->ignoreDestination();
}

/**
 * Implements hook_preprocess_HOOK() for attaching cache metadata to pages.
 *
 * This will attach cache metadata for vsites.
 */
function vsite_preprocess_page(&$variables, $hook) {
  /** @var \Drupal\vsite\Plugin\VsiteContextManagerInterface $vsite_context_manager */
  $vsite_context_manager = \Drupal::service('vsite.context_manager');
  /** @var \Drupal\group\Entity\GroupInterface|null $active_vsite */
  $active_vsite = $vsite_context_manager->getActiveVsite();

  if ($active_vsite) {
    $variables['#cache']['tags'] = Cache::mergeTags($variables['#cache']['tags'] ?? [], ['config:vsite.settings']);
  }
}

/**
 * Implements hook_preprocess_node().
 */
function vsite_preprocess_node(&$variables) {
  if ($variables['page']) {
    $app_manager = Drupal::service('vsite.app.manager');
    $app = $app_manager->getAppForBundle('node', $variables['node']->bundle());
    Drupal::service('os_widgets_context.context')->addApp($app);
  }
}

/**
 * Implements hook_preprocess_bibcite_reference().
 */
function vsite_preprocess_bibcite_reference(&$variables) {
  $entity = Drupal::requestStack()->getCurrentRequest()->attributes->get('bibcite_reference');
  // Checking the current request and rendered reference id match.
  if (!empty($entity) && $entity->id() == $variables['bibcite_reference']->id()) {
    $app_manager = Drupal::service('vsite.app.manager');
    $app = $app_manager->getAppForBundle('bibcite_reference', '*');
    Drupal::service('os_widgets_context.context')->addApp($app);
  }
}

/**
 * Implements hook_views_pre_render().
 */
function vsite_views_pre_render(ViewExecutable $view) {
  /** @var \Drupal\os_widgets_context\OsWidgetsContext $os_widget_context */
  $os_widget_context = Drupal::service('os_widgets_context.context');

  /** @var \Drupal\vsite\Plugin\AppManager $app_manager */
  $app_manager = Drupal::service('vsite.app.manager');
  $apps = $app_manager->getAppsForView($view);
  foreach ($apps as $app) {
    $os_widget_context->addApp($app);
  }
}

/**
 * Implements hook_group_insert() for a new vsite.
 */
function vsite_group_insert(GroupInterface $group) {
  // Call helper service.
  /** @var \Drupal\vsite\Helper\VsiteRoleHelper $role_helper */
  $role_helper = \Drupal::service('vsite.role_helper');

  $get_route_parameters = \Drupal::request()->attributes->all();
  // Admin role assignment is not required when creating from admin.
  if (isset($get_route_parameters['_route']) && $get_route_parameters['_route'] === 'entity.group.create') {
    // Assign admin role to owner.
    $role_helper->assignGroupAdminRoleToOwner($group);
  }
}
