<?php

/**
 * @file
 * Hook implementations for the os_pager module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function os_pager_theme($existing, $type, $theme, $path) {
  return [
    'os_views_pager' => [
      'variables' => [
        'tags' => [],
        'element' => 0,
        'parameters' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function os_pager_preprocess_os_views_pager(&$variables) {
  $element = $variables['element'];
  /** @var \Drupal\Core\Pager\PagerManager $pager_manager */
  $pager_manager = Drupal::service('pager.manager');
  $pager = $pager_manager->getPager($element);
  $current_page = $pager->getCurrentPage();
  $pager_total = $pager->getTotalPages();

  $tags = &$variables['tags'];
  $parameters = $variables['parameters'];

  // Current is the page we are currently paged to.
  $variables['items']['current'] = $current_page + 1;

  // If we have more than 1 page and we are not on the first.
  if ($pager_total > 1 && $current_page > 0) {
    $options = [
      'query' => $pager_manager->getUpdatedParameters($parameters, $element, $current_page - 1),
    ];
    $variables['items']['previous']['href'] = \Drupal::url('<current>', [], $options);
    if (isset($tags[1])) {
      $variables['items']['previous']['text'] = $tags[1];
    }
    $variables['items']['previous']['attributes'] = new Attribute();
  }

  // Actual page is less than last page.
  if ($current_page < ($pager_total - 1)) {
    $options = [
      'query' => $pager_manager->getUpdatedParameters($parameters, $element, $current_page + 1),
    ];
    $variables['items']['next']['href'] = \Drupal::url('<current>', [], $options);
    if (isset($tags[3])) {
      $variables['items']['next']['text'] = $tags[3];
    }
    $variables['items']['next']['attributes'] = new Attribute();
  }

  // This is based on the entire current query string. We need to ensure
  // cacheability is affected accordingly.
  $variables['#cache']['contexts'][] = 'url.query_args';

  $variables['pager_total'] = $pager_total;
  $variables['heading_id'] = Html::getUniqueId('pagination-heading');
}
