<?php

/**
 * @file
 * Hook implementations for the os_search module.
 */

use Drupal\search_api\Query\QueryInterface;

/**
 * Implements hook_search_api_query_alter().
 */
function os_search_search_api_query_alter(QueryInterface &$query) {
  // TODO: Get Group ID dynamically.
  $group_context = \Drupal::service('vsite.context_manager');
  $group = $group_context->getActiveVsite();

  if ($group) {
    $group_id = $group->id();
    $query->addCondition('custom_search_group', $group_id, '=');
  }

  if (!$group && !$query->getKeys()) {
    $query->addCondition('custom_search_group', 0, '=');
  }

}
