<?php

/**
 * @file
 * Hook implementations for the os_search module.
 */

use Drupal\search_api\Query\QueryInterface;

/**
 * Implements hook_theme().
 */
function os_search_theme($existing, $type, $theme, $path) {
  return [
    'os_filter_taxonomy_widget' => [
      'variables' => [
        'header' => '',
        'items' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_search_api_query_alter().
 */
function os_search_search_api_query_alter(QueryInterface &$query) {
  $search_query_builder = \Drupal::service('os_search.os_search_query_builder');
  $search_query_builder->queryBuilder($query);
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function os_search_group_insert($entity) {
  $search_helper = \Drupal::service('os_search.os_search_helper');
  $search_helper->createGroupBlockWidget($entity);
}
