<?php

/**
 * @file
 * OS Blog and Disqus alterations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function os_blog_form_node_blog_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  os_blog_node_blog_alter($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function os_blog_form_node_blog_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  os_blog_node_blog_alter($form, $form_state);
}

/**
 * Alters node blog form.
 *
 * @param array $form
 *   The form to alter.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function os_blog_node_blog_alter(array &$form, FormStateInterface $form_state) {
  $form['field_disqus_comments']['#access'] = FALSE;
  $form['field_disqus_comments']['widget'][0]['status']['#default_value'] = 0;
  $blog_comments_config = \Drupal::config('os_blog.settings');
  if ($blog_comments_config->get('comment_type') == 'disqus_comments') {
    $form['field_disqus_comments']['#access'] = TRUE;
    $form['field_disqus_comments']['widget'][0]['status']['#default_value'] = 1;
  }
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function os_blog_node_view_alter(array &$build, $entity, $display) {
  $blog_comments_config = \Drupal::config('os_blog.settings');
  if ($blog_comments_config->get('comment_type') == 'no_comments') {
    unset($build['field_disqus_comments']);
  }
}

/**
 * Implements hook_element_info_alter().
 */
function os_blog_element_info_alter(array &$info) {
  unset($info['disqus']['#pre_render']);
  $info['disqus']['#pre_render'][] = 'Drupal\os_blog\Element\DisqusOverride::generatePlaceholder';
}
